lazy val commonSettings = Seq(
  organization := "com.komanov",
  organizationHomepage := Some(url("https://komanov.com")),
  homepage := Some(url("https://dkomanov.github.io/scala-serialization/")),
  licenses := Seq(("MIT License", url("https://opensource.org/licenses/mit-license.html"))),
  startYear := Some(2016),
  scalaVersion := "2.11.12",
  resolvers += Resolver.bintrayRepo("evolutiongaming", "maven"),
  scalacOptions ++= Seq(
    "-deprecation",
    "-feature",
    "-Xmax-classfile-name", "240",
    //"-Xmacro-settings:print-serializers" //to log sources of serializaer which are generated by kryo-macros
    //"-Xmacro-settings:print-codecs" //to log sources of codecs which are generated by jsoniter-scala
  )
)

lazy val `scala-serialization-all` = project.in(file("."))
  .aggregate(`scala-serialization`, `scala-serialization-test`)

lazy val `scala-serialization` = project
  .settings(commonSettings: _*)
  .settings(
    fork in Test := true,
    libraryDependencies ++= Seq(
      "com.twitter" %% "util-core" % "18.3.0",
      "commons-io" % "commons-io" % "2.6",
      "com.evolutiongaming" %% "kryo-macros" % "1.1.8",
      "com.github.plokhotnyuk.jsoniter-scala" %% "macros" % "0.22.2",
      "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.5",
      "com.fasterxml.jackson.core" % "jackson-core" % "2.9.5",
      "com.fasterxml.jackson.dataformat" % "jackson-dataformat-cbor" % "2.9.5",
      "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.9.5",
      "com.google.protobuf" % "protobuf-java" % "3.0.0",
      "com.trueaccord.scalapb" %% "scalapb-runtime" % "0.5.45",
      "org.scala-lang.modules" %% "scala-pickling" % "0.11.0-M2",
      "io.suzaku" %% "boopickle" % "1.2.6",
      "com.twitter" %% "chill" % "0.9.2",
      "com.esotericsoftware" % "kryo-shaded" % "4.0.1", //for chill (should match with version for kryo-macros dependencies)
      "org.apache.thrift" % "libthrift" % "0.11.0",
      "org.slf4j" % "slf4j-simple" % "1.7.21", //for thrift
      "com.twitter" %% "scrooge-core" % "18.3.0",
      "org.specs2" %% "specs2-core" % "3.8.3" % Test,
      "org.specs2" %% "specs2-matcher-extra" % "3.8.3" % Test,
      "org.specs2" %% "specs2-mock" % "3.8.3" % Test,
      "org.specs2" %% "specs2-junit" % "3.8.3" % Test
    )
  )

lazy val `scala-serialization-test` = project
  .dependsOn(`scala-serialization`)
  .enablePlugins(JmhPlugin)
  .settings(commonSettings: _*)
  .settings(
    libraryDependencies ++= Seq(
      "pl.project13.scala" % "sbt-jmh-extras" % "0.3.3"
    )
  )
